name: github pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on:  windows-latest 
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        run:
          Invoke-WebRequest -Uri https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_Windows-64bit.zip -OutFile hugo_extended.zip
          Expand-Archive -Path hugo_extended.zip -DestinationPath $Env:ProgramFiles\Hugo
          $Env:Path += ";$Env:ProgramFiles\Hugo"


      - name: Build
        run: hugo --minify

    #   - name: Deploy
    #     uses: peaceiris/actions-gh-pages@v3
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: Back370/hugo-blog-dep.github.io
          publish_branch: main
          cname: back-2525.com
          verbose: true